### ISSUE TITLE
How to connect external css in different folder

### ISSUE THREAD

**Issue by Jbuan03** [KNapiza/BSIT-TSM-3A-IPT2IT-G6#2]
Guys do you have an idea how to connect a external CSS? Because my design.css is in the other file and It doesn't work for me...
![Issue](https://github.com/KNapiza/BSIT-TSM-3A-IPT2IT-G6/assets/159202025/bd8836f1-0c77-4336-8ec5-a197bb6f2400)

**Comment by KNapiza** [comment]
You can connect with it by just adding the folder before your CSS file just like this Foldername/file.css

**Comment by ShielaMaeEsquivel** [comment]
i agree with @KNapiza
